version: "3.2"
services:
    rabbitmq-server:
      image: rabbitmq:latest
      ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
      networks:
        - docclassifier
    ocr:
      build: ./ocr
      depends_on:
        - rabbitmq-server
      tty: true
      ports:
        - "9996:9996"
      volumes:
        - "./ocr:/ocr"
        - "./lib:/ocr/lib"
      environment:
        - RABBIT_HOST=rabbitmq-server
      networks:
        - docclassifier

    classifier:
      build: ./classifier
      depends_on:
        - rabbitmq-server
      tty: true
      ports:
        - "9998:9998"
      volumes:
        - "./classifier:/classifier"
        - "./lib:/classifier/lib"
      environment:
        - RABBIT_HOST=rabbitmq-server
      networks:
        - docclassifier
    ui:
      build: ./ui
      depends_on:
        - rabbitmq-server
        - classifier
        - ocr
      tty: true
      ports:
        - "9999:9999"
      volumes:
        - "./ui:/ui"
        - "./lib:/ui/lib"
      environment:
        - RABBIT_HOST=rabbitmq-server
      networks:
        - docclassifier

networks:
    docclassifier:
